// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use valid fallback URLs to prevent URL constructor errors
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://placeholder.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsYWNlaG9sZGVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NDUxOTI4MDAsImV4cCI6MTk2MDc2ODgwMH0.placeholder';

// Check if environment variables are properly configured
const isConfigured = import.meta.env.VITE_SUPABASE_URL && 
                    import.meta.env.VITE_SUPABASE_ANON_KEY &&
                    import.meta.env.VITE_SUPABASE_URL !== 'your_supabase_project_url_here' &&
                    import.meta.env.VITE_SUPABASE_ANON_KEY !== 'your_supabase_anon_key_here' &&
                    import.meta.env.VITE_SUPABASE_URL !== 'https://placeholder.supabase.co' &&
                    import.meta.env.VITE_SUPABASE_ANON_KEY !== 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsYWNlaG9sZGVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NDUxOTI4MDAsImV4cCI6MTk2MDc2ODgwMH0.placeholder';

if (!isConfigured) {
  console.warn('🔧 Supabase Configuration Required:');
  console.warn('1. Create a Supabase project at https://supabase.com/dashboard');
  console.warn('2. Go to Settings > API in your project');
  console.warn('3. Copy your Project URL and anon public key');
  console.warn('4. Update the .env file with your actual values');
  console.warn('5. Restart the development server');
  console.warn('');
  console.warn('Current values:');
  console.warn('VITE_SUPABASE_URL:', import.meta.env.VITE_SUPABASE_URL || 'not set');
  console.warn('VITE_SUPABASE_ANON_KEY:', import.meta.env.VITE_SUPABASE_ANON_KEY ? 'set (using placeholder)' : 'not set');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false
  }
});

// Export configuration status for other components to check
export const isSupabaseConfigured = isConfigured;